### PR TITLE
Add OPERA acknowledgement

### PR DESCRIPTION
**Pull request by peterdesmet**
- Dropped BALTRAD
- Added CC0 license
- Link to repository for instructions on how to cite (to be added)

### CODE REVIEW

**Comment by peterdesmet** [comment]
@adokter this PR contains a new intro to the repository in response to #32:

> ## ENRAM data repository for vertical profiles of birds
>
> This repository contains vertical profiles of birds (VP) generated by [vol2bird](https://github.com/adokter/vol2bird) from volume scans of over 100 weather radars in Europe. Access to the radar data was provided by the [European Operational Program for Exchange of Weather Radar Information (EUMETNET/OPERA)](http://eumetnet.eu/activities/observations-programme/current-activities/opera/) through a license agreement for research use with [ENRAM](http://enram.eu/) members.
> 
> Data in this repository are available under a [Creative Commons Zero waiver](https://creativecommons.org/publicdomain/zero/1.0/). We kindly ask you to acknowledge EUMETNET/OPERA in publications resulting from the use of these data. More information on how to browse, download, use, and cite these data [can be found here](https://github.com/enram/data-repository).

It covers:

1) What data it contains (vp by vol2bird from volume scans)
2) The scope (> 100 European radars)
3) That we got access to the radar data by EUMETNET/OPERA through a licence agreement.
4) How the vp data are legally licensed (is required, opted for CC0)
5) That for publication use specifically, we'd like to have EUMETNET/OPERA acknowledged
6) Links to GitHub (README) for further instructions

While keeping it moderately brief. It does not cover:

1) How to acknowledge EUMETNET/OPERA (suggested phrasing)
2) Caveats with the data (based on what @plieper has sent by email)
3) BALTRAD
4) References @adokter mentioned in #32

Which I suggest to add to the README (to be done). Optionally, I could also provide that README information in a pop-up on the repository when a user clicks "more information".

## Remaining questions/todo

* [ ] Any remarks on the intro? Wording, things I left out?
* [ ] Any remarks on the CC0 license? It's definitely the most appropriate for data (e.g. required by [Dryad](http://datadryad.org/)), but doesn't legally require attribution. Attribution/citation is a scientific norm, which is why I used "kindly ask you to acknowledge".
* [ ] Do we suggest people to **cite** or **acknowledge** EUMETNET/OPERA in their publications?? A citation would be to https://doi.org/10.1175/BAMS-D-12-00216.1, an acknowledgement would provide the option to be a bit more verbose (cf. suggested here: https://github.com/enram/data-repository/issues/32#issue-210503495) but is less impactful.
* [ ] Should people cite or acknowledge ENRAM or a link to the repository in their publication? Again, a citation would probably be to https://doi.org/10.1186/2051-3933-2-9 (not https://doi.org/10.1098/rsif.2010.0116, although we can mention that as a useful resource on how vps are generated), if we use an acknowledgement, we can actually bundle that with the one to EUMETNET/OPERA
* [ ] Preference for popup in addition to README?

**Comment by plieper** [comment]
I think 1,2 and 4 from the not-yet-covered list should be somewhere obvious, so if you think people will actually read the README, or click on the 'more info' button, both are fine for me. Or maybe you can make the 'more info' bottom something like 'essential info' button?

**Comment by peterdesmet** [comment]
Update with @adokter over Skype:

## ENRAM data repository for vertical profiles of birds

This repository contains vertical profiles of birds (VP) generated by [vol2bird](https://github.com/adokter/vol2bird) from volume scans of over 100 weather radars in Europe. Data in this repository are available under a [Creative Commons Zero waiver](https://creativecommons.org/publicdomain/zero/1.0/). Please acknowledge EUMETNET/OPERA in publications resulting from the use of these data as follows:

> We acknowledge [European Operational Program for Exchange of Weather Radar Information (EUMETNET/OPERA)](http://eumetnet.eu/activities/observations-programme/current-activities/opera/) for providing access to European radar data, faciliated through a research-only license agreement between EUMETNET/OPERA members and [ENRAM](http://enram.eu/).

More information on how to browse, download, and use these data [can be found on GitHub](https://github.com/enram/data-repository).

**Comment by peterdesmet** [comment]
Done in f3133f4. Site could be improved by only showing this on the home page, but it's more correct than before at least:

screen shot 2017-11-11 at 09 59 46

**Pull request merged**
